<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJOX5yw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJOX5yw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJOX5yw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJOX5yw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTJOX5yw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TJOX5yw',
    'container.build_id' => '4cb2a13d',
    'container.build_time' => 1551284158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJOX5yw');
