<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK4xrxZK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK4xrxZK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK4xrxZK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK4xrxZK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK4xrxZK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K4xrxZK',
    'container.build_id' => '1fac7d60',
    'container.build_time' => 1551272015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK4xrxZK');
